Изменение спецификации библиотеки
libsl-storage/wiki pull request #4
Opened 2023-04-01 09:35 UTC by m-malyarenko

2023-04-01 20:04 UTC, Reversean requested changes

2023-04-01 20:04 UTC, Reversean commented on README.md
> +Остальные элементы мета-информации для правок не доступны. В форме должна присутствовать опция "Настроить/Править". При нажатии на неё ооткрывается форма, содержащая в полях ввода текущие мета-данные
Давай разделять истории по частям системы, в которых они должны быть реализованы. Думаю здраво исходить из того, что система может использоваться не только через ui, но и через rest api бэкенда непосредственно. Также я бы наверное отдельно выделял истории, связанные с интеграциями структур данных в бд примерно по такой же причине. Это касается этой истории и всех последующих.

Да, я понимаю, что это выходит за рамки обычных user-story, и мы начинаем дополнять спеку излишними деталями, но впринципе почему бы и не использовать ее также для внутреннего пользования? Нам же нужно как-то документировать то, что мы собираемся реализовывать.

2023-04-01 20:04 UTC, Reversean commented on README.md
> +Остальные элементы мета-информации для правок не доступны. В форме должна присутствовать опция "Настроить/Править". При нажатии на неё ооткрывается форма, содержащая в полях ввода текущие мета-данные
> Языки реализации добавляются по кнопке \+ и выбираются из раскрывающегося списка.

Требуется задокументировать возможность добавлять кастомные языки, не присутствующие в списке.

2023-04-01 20:04 UTC, Reversean commented on README.md
> +При сохранении текста спецификации проверяется синтаксическая корректность. Вслучае синтаксических ошибок выводиться сообщение и диагностика, изменения откатываются.
"В случае" слитно написал

2023-04-01 20:04 UTC, Reversean commented on README.md
> +### STORY: Изменение владельцев спецификации
Требуется переформулировать. Мы не хотим делать несколько владельцев для одной спеки. Лучше давать права на изменения некоторых атрибутов спеки, при этом критические изменения оставлять доступными только одному владельцу (типа того же определения прав или удаления спеки).

2023-04-01 20:04 UTC, Reversean commented on README.md
> +  - Удаль текущую версию спецификации
Ошибка в слове "удалить".

2023-04-01 20:04 UTC, Reversean commented on README.md
> +При сохранении текста спецификации проверяется синтаксическая корректность. Вслучае синтаксических ошибок выводиться сообщение и диагностика, изменения откатываются.
А может нужна живая валидация? Алсо было бы не плохо бы задокументировать, что нужно рендерить по требованию пользователя превью визуализации спеки.

2023-04-01 20:04 UTC, Reversean commented on README.md
> +Остальные элементы мета-информации для правок не доступны. В форме должна присутствовать опция "Настроить/Править". При нажатии на неё ооткрывается форма, содержащая в полях ввода текущие мета-данные
На твоем месте, здесь и далее я бы не расписывал так детально дизайн, скорее всего его будешь реализовывать не ты. Распиши лучше, что должно быть в отображении, без конкретизации мест и формы представления.

2023-04-02 08:37 UTC, m-malyarenko commented on README.md
> +### STORY: Изменение владельцев спецификации
Выбрал не верный термин. Надо было назвать как-то вроде "Изменение прав доступа к спецификации". Я описывал как раз изменение прав доступа пользователей относительно конкретной спецификации.

2023-04-02 08:39 UTC, m-malyarenko commented on README.md
> +При сохранении текста спецификации проверяется синтаксическая корректность. Вслучае синтаксических ошибок выводиться сообщение и диагностика, изменения откатываются.
Думаю, что разработкой спецификации пользователь должен заниматься не в репозитории, а у себя на рабочей машине. Мы же на гитхабе код не пишем, хотя он предоставляет минимальные возможности по редактированию.

2023-04-02 08:47 UTC, m-malyarenko commented on README.md
> +Остальные элементы мета-информации для правок не доступны. В форме должна присутствовать опция "Настроить/Править". При нажатии на неё ооткрывается форма, содержащая в полях ввода текущие мета-данные
Добавил. Если так посмотреть, то поле языков реализации ничем принципиально от тэгов не отличается, просто в первом случае определён список и, соответственно, можно эти ярлычки языков как нибудь в UI подкрасить.

2023-04-02 08:50 UTC, m-malyarenko commented on README.md
> +Остальные элементы мета-информации для правок не доступны. В форме должна присутствовать опция "Настроить/Править". При нажатии на неё ооткрывается форма, содержащая в полях ввода текущие мета-данные
Убрал детали по UI. Писал их потому что в моем понимании user-story - это описание типичного процесса взаимодействия пользователя с ИС. У целевого пользователя уже сформировано представление как должен выглядеть репозиторий кода, ничего принципиально нового не придумать, жаи незачем.

2023-04-02 10:31 UTC, Reversean commented on README.md
> +Остальные элементы мета-информации для правок не доступны. В форме должна присутствовать опция "Настроить/Править". При нажатии на неё ооткрывается форма, содержащая в полях ввода текущие мета-данные
Не вижу решения этого вопроса.

2023-04-02 13:30 UTC, Reversean requested changes

2023-04-02 13:30 UTC, Reversean commented on README.md
> +При сохранении текста спецификации проверяется синтаксическая корректность. Вслучае синтаксических ошибок выводиться сообщение и диагностика, изменения откатываются.
Тогда возможно опустить возможность изменения при помощи текстового редактора?

2023-04-14 12:04 UTC, closed without merging